server:
  port: 9090
#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://10.1.102.155:3306/gxyj_166?useUnicode=true&characterEncoding=utf8
    username: gxyj_166_qa
    password: EQIn2iQ5UqCiVrdzb0nW
    driver-class-name: com.mysql.jdbc.Driver
#dubbo以及zookeeper配置
dubbo:
    application:
          name: zhy-provider
    registry:
          address: 10.1.102.164:2181
    protocol:
          port: 20874
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.model

#环境配置（开发，测试，生产）



