server:
  port: 9191
#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhy_166?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#dubbo以及zookeeper配置
dubbo:
    application:
          name: zhy-provider
    registry:
          address: 127.0.0.1:2181
    protocol:
          port: 20874
#uia:
    #registry:
          #ddress: 10.1.102.117:2181

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.model

#环境配置（开发，测试，生产）



