server:
  port: 9191
#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://114.115.135.120:3306/medical_shaoer?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root526
    driver-class-name: com.mysql.jdbc.Driver
#dubbo以及zookeeper配置
dubbo:
    application:
          name: zhy-provider
    registry:
          address: 106.13.97.149:2181
    protocol:
          port: 20874
#uia:
    #registry:
          #ddress: 10.1.102.117:2181

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.model

#环境配置（开发，测试，生产）



