server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://10.1.102.155:3306/gxyj_166?useUnicode=true&characterEncoding=utf8
    username: gxyj_166_qa
    password: EQIn2iQ5UqCiVrdzb0nW
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
    application:
          name: zhy-provider
    registry:
          address: 10.1.102.166:2181
    protocol:
          port: 20874
mybatis:
  mapper-locations: classpath:mybatis/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.model  # 注意：对应实体类的路径


